url: https://y7kim.github.io
baseurl:

# Site settings
title: Smart Scaffolding MQP
email: cwagner@wpi.edu
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
people:
  - name: Caleb Wagner
    pic: 1
    position: Software Engineer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: stack-overflow
        url: #

  - name: Ben Liang
    pic: 2
    position: Software Engineer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: linkedin
        url: #

  - name: Neel Dhanaraj
    pic: 3
    position: Mechanical Engineer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: google-plus
        url: #

  - name: Cameron Collins
    pic: 1
    position: Mechanical Engineer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: stack-overflow
        url: #

  - name: Josue Contreras
    pic: 2
    position: Electrical Engineer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: linkedin
        url: #

  - name: Trevor Rizzo
    pic: 3
    position: Electrical Engineer
    social:
      - title: twitter
        url: #
      - title: facebook
        url: #
      - title: google-plus
        url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 5 Hackfeld Road
  - line: Worcester, MA 01609

# Build settings
markdown: kramdown
permalink: pretty
